export const site = {
  name: "Breakthrough TMS",
  logo: "/images/logo.webp",
  logo2x: "/images/logo@2x.webp",
  logoFooter: "/images/logo-footer.webp",
  wallpaper: "/images/wallpaper-monogram.webp",
  /** Twilio tracking number — replace when assigned */
  phone: "(818) 793-5067",
  phoneHref: "tel:+18187935067",
  fax: "(818) 793-5094",
  address: "100 W Broadway #1050, Glendale, CA 91210",
  addressLines: ["100 W Broadway #1050", "Glendale, CA 91210"],
  hours: {
    days: "Monday – Friday",
    time: "7:00 AM – 7:00 PM",
    display: "Monday – Friday, 7:00 AM – 7:00 PM",
  },
  website: "https://www.breakthroughtms.com",
  email: "info@tmsbreakthrough.com",
  emailHref: "mailto:info@tmsbreakthrough.com",
  mapsUrl: "https://maps.google.com/maps?q=Breakthrough%20Tms&t=m&z=15",
  mapsEmbedUrl:
    "https://maps.google.com/maps?q=%20Breakthrough%20Tms&t=m&z=15&output=embed&iwloc=near",
  parkingNote: "Validated parking near Americana at Brand",
  serviceAreas: [
    "Glendale",
    "Burbank",
    "Pasadena",
    "North Hollywood",
    "Sherman Oaks",
    "San Fernando Valley",
  ],
  routes: {
    bookConsult: "/#book-consult",
    qualify: "/#qualify",
    inquiry: "/#qualify",
    patientStories: "/#patient-stories",
    meetDoctor: "/#meet-doctor",
  },
  images: {
    drSaakyan: "/images/dr-artur-saakyan.jpeg",
    faqOffice: "/images/breakthrough-tms-office.webp",
    patientInRoom: "/images/patient-in-room.webp",
    treatmentSession: "/images/treatment-session.webp",
    storyEmma: "/images/story-emma.webp",
    storyRonda: "/images/story-ronda.webp",
    storyCathy: "/images/story-cathy.webp",
    storyVictor: "/images/story-victor.webp",
  },
  ghl: {
    calendarName: "Book your Free Consultation",
    origin: "https://go.4tms.com",
    embedScriptSrc: "https://go.4tms.com/js/form_embed.js",
    calendar: {
      id: "PLACEHOLDER_CALENDAR",
      iframeId: "PLACEHOLDER_CALENDAR_IFRAME",
      src: "https://go.4tms.com/widget/booking/PLACEHOLDER_CALENDAR",
      title: "Book your Free Consultation",
    },
    inquiryForm: {
      id: "PLACEHOLDER_FORM",
      iframeId: "inline-PLACEHOLDER_FORM",
      name: "Breakthrough TMS: Qualification Inquiry",
      title: "Find out if you Qualify",
      src: "https://go.4tms.com/widget/form/PLACEHOLDER_FORM",
      height: 1200,
    },
  },
} as const;
